### ISSUE TITLE
Improve the game

### ISSUE THREAD

**Issue by nasivuela** [Adalab/f-m2-evaluacion-intermedia-sandrapinazo#1]
Beautifully done @sandrapinazo  !!!

Here you have some tips to improve the exercise:

- [x] Improve organization of constants and variables, maybe first constants with elements, then rest of constants, and finally variables?
- [x] Add a white line after 'use strict' to improve readability
- [x] You are writing many times "hintText.innerHTML = 'something';", what about making a function that accepts a string as param and paints it into 'hintText'?
- [x] Indent and remove logs to have an even cleaner code.
- [x] Use a `label` to define the content of the input

Then you can improve the game as you please, here you have some ideas:

- Add new feedback when the number is bigger than 100 or smaller than 0.
- Manage when the user hits the button and the input is empty.
- Make the input work when hitting enter key.
- Add a reset button that cleans the input, the counter, writes the initial feedback and generates a new random number to play again!
- Whatever you want!

Let me know if you have any doubts ;)

Go for it!!

**Comment by sandrapinazo** [comment]
Fixed most of the issues and improvements!
I still need to add feedback for a number bigger than 100 or smaller than 0, a reset button and try to work on a better css and design for the game.

**Comment by nasivuela** [comment]
Good work @sandrapinazo !!

Do not forget to organize your files in folders ;) Suggestions at the end of lesson 1 of module 1.

![](https://media.giphy.com/media/cXaeWuJ1oKO4g/giphy.gif)
